apiVersion: 1

datasources:
  - name: Prometheus
    uid: cortex-prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_DATASOURCE_URL}
    isDefault: true
    editable: false
